- name: install xfce4 minimal packages
  apt: name="{{ item }}" state="present"
  with_items: "{{ xfce4_debian_packages }}"

- name: install xfce4 extra packages
  apt: name="{{ item }}" state="present"
  with_items: "{{ xfce4_debian_extra_packages }}"

- name: restart lightdm service
  service: name="{{ xfce4_login_manager }}" state="restarted"
