- apt: name="{{ item }}" state="present"
  with_items: "{{ xfce4_ubuntu_packages }}"
  notify: "restart lightdm"

- apt: name="{{ item }}" state="present"
  with_items: "{{ xfce4_ubuntu_extra_packages }}"
  notify: "restart lightdm"
